### ISSUE TITLE
Move Search Model Methods into Client

### ISSUE THREAD

**Issue by wollerman** [noahtren/noms#5]
The `noms.search` module seems to depend explicitly on the client. And it seems better to leave these methods up to the client. The usage of doing:
```
import noms
client = noms.Client("api key")
search_results = noms.get_results("Raw Broccoli", client)
```

seems a little confusing compared to doing:

```
import noms
client = noms.Client("api key")
search_results = client.get_results("Raw Broccoli")
```

Is there a reason you pulled these out into a top level module? It feels more OO to call methods on the client.

**Comment by noahtren** [comment]
Thanks for opening this issue! I remember debating between these two implementations and I chose to pass the client as a parameter just to keep all of the methods being called from the main package. This doesn't make sense if get_results() can only be called explicitly with a client object, so I've changed it to the more OO version.

Thanks :)
