### ISSUE TITLE
Refactor print_results into results object __str__() method

### ISSUE THREAD

**Issue by wollerman** [noahtren/noms#6]
It would be more python to make the print for results not need a special method name for users to remember. For example, it would be much more likely for me to try:
```
search_results = noms.get_results("Raw Broccoli", client)
print(search_results)
```

And this can be achieved by defining a class for your results and then defining `__str__()` on that class. Even if that class is simply a simple dict wrapper, it can make your API more friendly to interact with.

Just a thought :)

**Comment by noahtren** [comment]
Thank you for suggesting this! This is much more Pythonic, and admittedly something I wasn't even aware of. There is now a class SearchResults in `noms/client/main.py` which serves this purpose. Thank you.
